name: zhijian
description: zhijian gl hf.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #国际化
  intl: ^0.18.1
  #包含dart:collection样式的实用函数和类，使使用集合更容易。
  collection:
  #包信息
  package_info_plus: ^4.2.0
  #原生分享
  share_plus: ^7.2.1
  #网络请求
  dio: ^5.3.3
  #官方路由
  go_router: ^12.0.0
  #状态
  flutter_riverpod: ^2.4.4
  #屏幕适配
  flutter_screenutil: ^5.9.0
  #简单数据持久化
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  #loading
  bot_toast: ^4.1.3
  #webview升级版`
  flutter_inappwebview: ^5.8.0
  #文字动画
  animated_text_kit: ^4.2.2
  #可见性
  visibility_detector: ^0.4.0+2
  #官方视频播放器
  video_player: ^2.7.2
  #亮度调节
  screen_brightness: ^0.2.2+1
  #常亮
  wakelock_plus: ^1.1.3
  #视频截图
  video_thumbnail: ^0.5.3
  #喜欢widget
  like_button: ^2.0.5
  #主题
  flex_color_scheme: ^7.3.1
  #文件系统目录
  path_provider: ^2.1.1
  #打开email 网站等
  url_launcher: ^6.2.0
  #裁剪
  image_cropping: ^0.0.13
  #打开相册
  image_picker: ^1.0.4
  #动态权限
  permission_handler: ^11.0.1
  #文件下载和打开
  flutter_downloader: ^1.11.4
  #图片缓存
  cached_network_image: ^3.3.0
  #html标签解析
  flutter_html: ^3.0.0-beta.2
  #显示更多内容
  readmore: ^2.2.0
  #loading 加载指示器集合
  flutter_spinkit: ^5.2.0
  #替换pull refresh
  easy_refresh: ^3.3.2+1
  # freezed相关
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  #网络请求日志
  #pretty_dio_logger: ^1.1.1
  #播放器 弃用
  #chewie: ^1.4.0
  #打开文件
  #open_file: ^3.2.1
  #事件总线
  #event_bus: ^2.0.0
  #webview
  #webview_flutter: ^2.1.1
  #cupertino_icons: ^1.0.2
  #加密库
  #crypto: ^3.0.1
  #编码
  #convert: ^3.0.0
  #cookie_jar: ^3.0.1
  #dio_cookie_manager: ^2.0.0
  #dio_cache_interceptor: ^2.3.1
  #网络状态
  #connectivity_plus: ^2.2.0
  #设备信息
  #device_info_plus: ^3.2.1
  #markdwon支持
  #flutter_markdown: ^0.6.6
  #预加载pageview
  #preload_page_view: ^0.1.6
  #官方推荐数据库
  #sqflite: ^2.0.2
  #通知栏
  #awesome_notifications: ^0.7.4+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  #freezed相关
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/images/
    - assets/json/
flutter_intl:
  enabled: true